version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-auth
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - emqx
      - influxdb
    networks:
      - red-auth
    environment:
      - EMQX_API_BASE=http://emqx:8081/api/v4
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__USERNAME=admin
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__PASSWORD=admin123..
      - INFLUX_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_ORG=my-org
      - INFLUX_BUCKET=measurements

  mongo:
    image: mongo:5.0
    container_name: auth-mongo
    restart: always
    volumes:
      - auth-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - red-auth
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8082"  
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    command: ["node", "app", "--port", "8082"]  
    depends_on:
      - mongo
    networks:
      - red-auth

  emqx:
    image: emqx/emqx:4.4.18
    container_name: emqx
    restart: unless-stopped
    networks:
      - red-auth

    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
      - "8081:8081"

    environment:
      - EMQX_NAME=emqx
      # --- CONFIGURACIÓN GENERAL ---
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_LOADED_PLUGINS=emqx_management,emqx_dashboard,emqx_auth_mongo
      - EMQX_LOG__LEVEL=debug  # Activar logs detallados
      # --- Habilita auth_mongo y datos de conexión ---
      - EMQX_AUTH__MONGO__ENABLE=true
      - EMQX_AUTH__MONGO__SERVER=auth-mongo:27017
      - EMQX_AUTH__MONGO__USERNAME=root
      - EMQX_AUTH__MONGO__PASSWORD=example
      - EMQX_AUTH__MONGO__DATABASE=iot

      # --- Colección de usuarios ---
      - EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION=mqtt_user
      - EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR=username=%u
      - EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD=password
      - EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH=bcrypt

      # --- Colección ACL (mqtt_acl) ---
      - EMQX_AUTH__MONGO__ACL_QUERY=on
      - EMQX_AUTH__MONGO__ACL_QUERY__DATABASE=iot
      - EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION=mqtt_acl
      - EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR=username=%u
      - EMQX_AUTH__MONGO__ACL_QUERY__TOPIC_FIELD=topic

      # Opcionales para desarrollo:
      - EMQX_AUTH__MONGO__ACL_QUERY__CACHE_ENABLE=false
      - EMQX_AUTH__MONGO__ACL_QUERY__TOPIC_FUZZY=true

      # acceso a dashboard
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=admin123..
      - EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET=admin123..
    depends_on:
      - mongo


  influxdb:
    image: influxdb:2.6
    container_name: influxdb

    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123..
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=measurements
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin123
    networks:
      - red-auth
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # credenciales de Grafana
      - GRAFANA_ADMIN_USER=admin
      - GRAFANA_ADMIN_PASSWORD=admin123..
      - GRAFANA_URL=http://grafana:3000
      # Credenciales de administrador de Grafana
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123..
      # Deshabilitar anonimato y habilitar autenticación básica
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - red-auth

volumes:
  auth-mongo-data:
  influxdb-data:
  grafana-data:

networks:
  red-auth:


